cmake_minimum_required(VERSION 3.16)
# Run at application configure time and in offline tests. Resolve local includes,
# including basename includes, so relative-path spelling cannot bypass layer checks.
if(NOT ARCHITECTURE_SOURCE_ROOT)
    message(FATAL_ERROR "ARCHITECTURE_SOURCE_ROOT is required")
endif()
get_filename_component(ARCHITECTURE_SOURCE_ROOT "${ARCHITECTURE_SOURCE_ROOT}" ABSOLUTE)
file(GLOB_RECURSE architecture_files
    "${ARCHITECTURE_SOURCE_ROOT}/*.h" "${ARCHITECTURE_SOURCE_ROOT}/*.cpp")
foreach(source IN LISTS architecture_files)
    get_filename_component(name "${source}" NAME)
    string(MAKE_C_IDENTIFIER "${name}" key)
    list(APPEND architecture_header_${key} "${source}")
endforeach()
foreach(source IN LISTS architecture_files)
    file(RELATIVE_PATH layer "${ARCHITECTURE_SOURCE_ROOT}" "${source}")
    if(layer MATCHES "^service/oscilloscopestrategy/")
        file(READ "${source}" strategy_source)
        if(strategy_source MATCHES "(writeConfigurationCommand|queryConfiguration|sendCommand|queryString|queryDouble|queryRaw|measureSignalPeak|getTriggerSource|getTriggerState|getAcquisitionState|model)[ \t\r\n]*\\(" OR
           strategy_source MATCHES "\"(:)?([Tt][Rr][Ii][Gg][Gg][Ee][Rr]:|[Aa][Cc][Qq][Uu][Ii][Rr][Ee]:|[Mm][Ee][Aa][Ss][Uu][Rr][Ee][Mm][Ee][Nn][Tt]:|CH%[0-9]:)")
            message(FATAL_ERROR "Oscilloscope protocol in strategy layer: ${layer}")
        endif()
    endif()
    if(layer MATCHES "^service/(capture/|testrun/|oscilloscope/(manualscopecontrol|oscilloscopeconfiguration)\\.)")
        file(READ "${source}" capability_source)
        if(capability_source MATCHES "(writeConfigurationCommand|queryConfiguration|sendCommand|queryString|queryDouble|queryRaw|measureSignalPeak|getTriggerSource|getTriggerSlope|getAcquisitionState)[ \t\r\n]*\\(" OR
           capability_source MATCHES "\"(:)?([Tt][Rr][Ii][Gg][Gg][Ee][Rr]:|[Aa][Cc][Qq][Uu][Ii][Rr][Ee]:|[Hh][Oo][Rr][Ii][Zz][Oo][Nn][Tt][Aa][Ll]:|CH%[0-9]:)")
            message(FATAL_ERROR "Oscilloscope protocol outside driver capability: ${layer}")
        endif()
    endif()
    get_filename_component(directory "${source}" DIRECTORY)
    file(STRINGS "${source}" includes REGEX "^[ \t]*#[ \t]*include[ \t]*[<\"]")
    foreach(line IN LISTS includes)
        string(REGEX REPLACE "^[ \t]*#[ \t]*include[ \t]*[<\"]([^>\"]+)[>\"].*$" "\\1" header "${line}")
        if(layer MATCHES "^(data|models|viewmodels|service|infrastructure|hardware)/" AND
           header MATCHES "^(QtWidgets(/|$)|Q(Widget|Dialog|MainWindow|MessageBox|TableView|TableWidget|PushButton|ComboBox|LineEdit|SpinBox|FileDialog|Application|TabWidget|Label|FormLayout|VBoxLayout|HBoxLayout)$)")
            message(FATAL_ERROR "UI dependency in non-UI layer: ${layer} -> ${header}")
        endif()
        if(layer MATCHES "^data/" AND header MATCHES "^Q(File|FileInfo|Dir|SaveFile|Process)$")
            message(FATAL_ERROR "I/O dependency in data layer: ${layer} -> ${header}")
        endif()
        set(destinations "")
        if(EXISTS "${directory}/${header}")
            get_filename_component(resolved "${directory}/${header}" ABSOLUTE)
            list(APPEND destinations "${resolved}")
        else()
            get_filename_component(name "${header}" NAME)
            string(MAKE_C_IDENTIFIER "${name}" key)
            set(destinations ${architecture_header_${key}})
        endif()
        foreach(destination IN LISTS destinations)
            file(RELATIVE_PATH dependency "${ARCHITECTURE_SOURCE_ROOT}" "${destination}")
            set(forbidden FALSE)
            if(layer MATCHES "^data/" AND NOT dependency MATCHES "^data/")
                set(forbidden TRUE)
            elseif(layer MATCHES "^models/" AND NOT dependency MATCHES "^(data|models)/")
                set(forbidden TRUE)
            elseif(layer MATCHES "^(viewmodels|service|infrastructure|hardware)/" AND dependency MATCHES "^(views|ui)/")
                set(forbidden TRUE)
            elseif(layer MATCHES "^hardware/" AND dependency MATCHES "^(views|viewmodels|models|service)/")
                set(forbidden TRUE)
            elseif(layer MATCHES "^service/oscilloscopestrategy/" AND dependency MATCHES "^hardware/" AND
                   NOT dependency MATCHES "/(iscopemeasurement|iscopeperiodsession)\\.h$")
                set(forbidden TRUE)
            elseif(layer MATCHES "^service/oscilloscope/manualscopecontrol\\." AND dependency MATCHES "^hardware/" AND
                   NOT dependency MATCHES "/iscopemanualcontrol\\.h$")
                set(forbidden TRUE)
            elseif(layer MATCHES "^service/oscilloscope/oscilloscopeconfiguration\\." AND dependency MATCHES "^hardware/")
                set(forbidden TRUE)
            elseif(layer MATCHES "^service/capture/" AND dependency MATCHES "^hardware/instrument/" AND
                   NOT dependency MATCHES "/iscopecapture\\.h$")
                set(forbidden TRUE)
            elseif(layer MATCHES "^(views/|ui/controller/)" AND dependency MATCHES "^hardware/" AND
                   NOT dependency MATCHES "/(oscilloscope|iscopemeasurement|iscopecapture|instrumentwithcommbase|icommunication)\\.h$")
                set(forbidden TRUE)
            endif()
            if(forbidden)
                message(FATAL_ERROR "Forbidden layer dependency: ${layer} -> ${dependency}")
            endif()
        endforeach()
    endforeach()
endforeach()

function(check_headless_target target visited)
    if(NOT TARGET "${target}" OR target IN_LIST visited)
        return()
    endif()
    list(APPEND visited "${target}")
    foreach(property LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
        get_target_property(dependencies "${target}" ${property})
        foreach(dependency IN LISTS dependencies)
            string(REGEX REPLACE "^\\$<LINK_ONLY:([^>]+)>$" "\\1" dependency "${dependency}")
            if(dependency MATCHES "Widgets|[Vv][Ii][Ss][Aa]")
                message(FATAL_ERROR "Headless target ${target} depends on ${dependency}")
            endif()
            check_headless_target("${dependency}" "${visited}")
        endforeach()
    endforeach()
endfunction()
foreach(target IN LISTS ELECTRONICATE_CORE_TARGETS)
    check_headless_target("${target}" "")
endforeach()
if(TARGET ElectronicATEDrivers)
    check_headless_target(ElectronicATEDrivers "")
endif()
